apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
    version: v1.3.0-alpha.5
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-scheduler
        version: v1.3.0-alpha.5
    spec:
      containers:
      - name: kube-scheduler
        image: quay.io/peanutbutter/hyperkube:v1.3.0-alpha.5_derek.1
        command:
        - ./hyperkube
        - scheduler
        - --leader-elect=true
